services:
  # 1. NestJS ilovasi servisi
  server:
    build: .
    container_name: property_server
    environment:
      - MONGODB_URL=mongodb://mongo:27017/property
      - JWT_SECRET=7f4c1a7a9c2b37e8d44a8b0a3c9ef6a63d2f5e6a91b8c3a4d5f6e7a8b9c0d1e2
      - NODE_ENV=
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USERNAME=tilavuz@gmail.com
      - EMAIL_PASSWORD=cvhs vodx bdwc zxtv
      - DEFAULT_FROM=tilavuz@gmail.com
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  # 2. MongoDB ma'lumotlar bazasi servisi
  mongo:
    image: mongo:latest
    container_name: property_mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  # 3. Nginx (Reverse Proxy) servisi
  nginx:
    image: nginx:latest
    container_name: property_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
